version: "3.8"
services:
  nginx:
    depends_on:
      - php-fpm
      - node
    restart: always
    container_name: ${PROJECT_NAME}-nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./backend:/www
    ports:
      - "${DEV_FRONTEND_PORT}:9999"
      - "${SSL_EXTERNAL_PORT}:443"
      - "${HTTP_EXTERNAL_PORT}:80"
    networks:
      app:
        aliases:
          - nginx
    build:
      context: ./
      dockerfile: ./nginx/Dockerfile
  php-fpm:
    restart: always
    container_name: ${PROJECT_NAME}-php-fpm
    volumes:
      - ./backend:/www
    networks:
      app:
        aliases:
          - php-fpm
    build:
      context: ./
      dockerfile: ./php/Dockerfile
  node:
    restart: always
    container_name: ${PROJECT_NAME}-node
    volumes:
      - ./frontend:/www
    build:
      context: ./
      dockerfile: ./node/Dockerfile
    networks:
      app:
        aliases:
          - node
networks:
  app:
    name: "${PROJECT_NAME}-app"
